apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-convert
  labels:
    app: pdf-convert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-convert
  template:
    metadata:
      labels:
        app: pdf-convert
    spec:
      containers:
      - name: pdf-convert
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/pdf-convert:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
        env:
        - name: PDF_LICENSE_PATH
          valueFrom:
            secretKeyRef:
              name: pdf-convert-secrets
              key: license-path
        volumeMounts:
        - name: license-volume
          mountPath: /work/license
          readOnly: true
      volumes:
      - name: license-volume
        secret:
          secretName: pdf-convert-secrets
          items:
          - key: license
            path: license.xml
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-convert
spec:
  selector:
    app: pdf-convert
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-convert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-convert
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 